HathorNetwork/tx-mining-service

.gitignore, poetry.lock, pyproject.toml, tests/test_filters.py, txstratum/api.py, txstratum/cli.py, txstratum/filters.py, txstratum/toi_client.py
Create a client for toi service
=> feat(api): Add toi client

txstratum/cli.py
- It should be possible to pass a flag that enables logs in JSON format
=> feat: Allow logging in json

docs/apidocs.yml, pyproject.toml
- https://github.com/HathorNetwork/tx-mining-service/pull/45
- https://github.com/HathorNetwork/tx-mining-service/pull/44
=> chore: bump v0.2.0

txstratum/protocol.py
Although this may sound undesirable, our patches on cgminer/ccminer/cpuminer don't support using a different address per stratum server. So this is a workaround to allow a single miner to be shared on a mainnet tx-mining-service and a testnet tx-mining-service, which is exactly what I'm doing with my USB ASIC.
=> feat: accept address from wrong network

txstratum/cli.py, txstratum/manager.py
- It should be possible to configure the "block template update interval" through cli args or env vars
In some cases we will need to increase this interval to avoid sending too many requests to the fullnode
=> feat: allow setting block template update interval

README.md
- Add docs explaining briefly some important topics about how the service works
=> docs: how it works

txstratum/protocol.py
issue: https://github.com/HathorNetwork/internal-issues/issues/83
- The memory usage should stop increasing when running the service
=> fix: memory leak

Dockerfile, docs/apidocs.yml, pyproject.toml
- Add `libgcc` needed at runtime
- Bump version to v0.6.4
=> fix: missing deps

docs/apidocs.yml, poetry.lock, pyproject.toml, tests/test_api.py, tests/test_manager.py, txstratum/jobs.py, txstratum/manager.py
- https://github.com/HathorNetwork/tx-mining-service/pull/78
- https://github.com/HathorNetwork/tx-mining-service/pull/76
=> release: v0.7.0

docs/apidocs.yml, pyproject.toml
=> chore: bump to v0.8.1

docs/apidocs.yml, pyproject.toml
- https://github.com/HathorNetwork/tx-mining-service/pull/84
=> bump: v0.8.2

tests/test_api.py, txstratum/middleware.py
https://github.com/HathorNetwork/internal-issues/issues/118
- We must have a new header handling in order to skip the wallet version check if a specific criteria is match
=> feat: allow request to send header to skip wallet version check

docs/apidocs.yml, pyproject.toml
- https://github.com/HathorNetwork/tx-mining-service/pull/94
=> bump: v0.9.1

.github/workflows/main.yml, docs/apidocs.yml, poetry.lock, pyproject.toml, txstratum/protocol.py, txstratum/utils.py
- https://github.com/HathorNetwork/tx-mining-service/pull/94
=> Release: v0.9.1

docs/apidocs.yml, pyproject.toml
Depends on https://github.com/HathorNetwork/tx-mining-service/pull/101
- Bump package to version v0.11.0
=> chore: bump package version to v0.11.0

docs/apidocs.yml, poetry.lock, pyproject.toml, tests/test_api.py, txstratum/api.py, txstratum/jobs.py, txstratum/utils.py
=> Release v0.11.0

docs/apidocs.yml
We should add the new `/health` endpoint in the API docs.
The endpoint was implemented in https://github.com/HathorNetwork/tx-mining-service/pull/104
=> docs: add healthcheck

docs/apidocs.yml, pyproject.toml
- https://github.com/HathorNetwork/tx-mining-service/pull/104
- https://github.com/HathorNetwork/tx-mining-service/pull/105
- https://github.com/HathorNetwork/tx-mining-service/pull/106
=> bump: v0.12.0

docs/apidocs.yml, pyproject.toml
=> chore: bump package to v0.13.0

docs/apidocs.yml, pyproject.toml
- Release v0.13.0 (because of an error, the other PRs have already been merged to `master` before)
=> Release v0.13.0

txstratum/protocol.py
- Stop rtt estimator periodic task on connection lost.
Fixes https://github.com/HathorNetwork/internal-issues/issues/443
=> fix: stop rtt estimator task on connection lost

docs/apidocs.yml, pyproject.toml
- Bump package version to v0.13.1
=> chore: bump package version to v0.13.1

docs/apidocs.yml, pyproject.toml, txstratum/protocol.py
- Start release process of v0.13.1
https://github.com/HathorNetwork/tx-mining-service/pull/120
=> Release v0.13.1

docs/apidocs.yml, pyproject.toml
=> chore: bump package to v0.14.0

docs/apidocs.yml, pyproject.toml
- Release v0.14.0
https://github.com/HathorNetwork/tx-mining-service/pull/123 (this PR was incorrectly merged directly to master)
=> Release v0.14.0

docs/apidocs.yml, pyproject.toml
=> chore: bump package to v0.14.1

Dockerfile, docs/apidocs.yml, pyproject.toml
=> Release v0.14.1

docs/apidocs.yml, pyproject.toml
- Bump package to v0.15.0
Release PRs:
- [Add support to mine ocb txs](https://github.com/HathorNetwork/tx-mining-service/pull/130)
=> chore: bump package to v0.15.0

docs/apidocs.yml, poetry.lock, pyproject.toml
- Release v0.15.0
Release PRs:
- [Add support to mine ocb txs](https://github.com/HathorNetwork/tx-mining-service/pull/130)
=> Release v0.15.0

txstratum/cli.py
The tx-mining-service silently broke because settings were silently being loaded too early.
- Move every import that can cause a settings load to the function that needs it (only needed in `txstratum/cli.py`)
- Add `self.settings` to cause errors earlier next time
- Include `network=self.settingsNETWORK_NAME` to the `API Configuration` log
=> fix(cli): ensure settings only load (even indirectly) after arg parsing

docs/apidocs.yml, poetry.lock, pyproject.toml
- Release v0.15.1
PRs: https://github.com/HathorNetwork/tx-mining-service/commit/ec6a80a5c8c4659a4e2940f2960c55220ef52ec8
=> Release v0.15.1

poetry.lock, pyproject.toml
- https://github.com/HathorNetwork/tx-mining-service/pull/140
=> Release v0.16.1

pyproject.toml
=> chore: bump tx mining package to v0.16.2

pyproject.toml, txstratum/jobs.py
- Release v0.16.2
- https://github.com/HathorNetwork/tx-mining-service/pull/142
=> Release v0.16.2

poetry.lock, pyproject.toml
- https://github.com/HathorNetwork/tx-mining-service/pull/145
=> Release v0.17.0

pyproject.toml
- Bump package version to v0.19.0
=> chore: bump version to v0.19.0
