HathorNetwork/tx-mining-service

- tests/manager.py
- txstratum/manager.py
When a transaction is received to be mined, the tx mining service estimates how long it will take to get it done and saves it to `job.expected_mining_time`. If this time cannot be calculated, this value is set to `-1`.
Finally, when there's a queue of transactions, we sum the individual `expected_mining_time` of the transactions to calculate the `job.expected_queue_time`. In this case, we must ignore the transactions with `-1` value.
We found out this bug when many transactions had `expected_mining_time = -1` and new transactions were summing and setting the `expected_queue_time` to negative values (e.g., -7, -9, -17).
> fix: Only consider positive mining time when estimating queue time

- tests/api.py
- tests/manager.py
- tests/prometheus.py
- txstratum/cli.py
- txstratum/commons/client.py
- txstratum/commons/exceptions.py
- txstratum/commons/utils.py
- txstratum/manager.py
- txstratum/protocol.py
It doesn't make sense to mine blocks without an output, and to generate an output we need an address. Even though it is very unlikely that the tx-mining-service will find a block in Hathor's mainnet, it is also used to mine blocks in the testnet where it indeed find many blocks.
> feat(backend): Backend's get_block_template must give an address for the block

- txstratum/jobs.py
Even though I don't like this solution, it should work for most cases. A definite solution will use the new mining api (`/v1a/mining_ws`) that includes the min and max timestamp but it requires a new version of the `HathorClient` and I'd like to refactor and move the `commons/` directory to another repository `hathor-commons` to be shared between projects.
It solves https://github.com/HathorNetwork/hathor-core/issues/174
> fix: Block timestamp cannot be updated when the latest block has been found a long time ago

- tests/manager.py
- txstratum/constants.py
- txstratum/utils.py
When a miner connects to the tx mining service, its hashrate is unknown and it will be discovered after a few iterations in the difficulty adjustment loop. Usually it takes ~30 seconds to find a reasonable estimate for the hashrate.
Currently, when the total hashrate of the miners is unknown, we set the `job.expected_mining_time` to `-1`.
This pull request intends to fix a problem that happens when several transactions are arriving to be mined and we restart the tx mining service. In this case, all miners will reconnect and their hashrate will be unknown. At the same time, several transactions will arrive and will have `expected_mining_time = -1`. In this case, the wallets will show an error message saying that "No miners are available" while the tx mining service will actually solve …
> fix: Estimate tx-mining-time when the total hashrate of the miners is unknown

- tests/test_manager.py
- txstratum/api.py
- txstratum/commons/base_transaction.py
- txstratum/jobs.py
- txstratum/manager.py
- txstratum/protocol.py
This PR fixes three issues: (i) invalid jobs, (ii) stale jobs, and (iii) invalid shares.
**invalid_jobs**: This issue happened when the weight was an integer number. As the job is a json sent to the miner, the miner had a deserialization problem.
**stale jobs**: This issue happened when mining blocks and either the block's timestamp was updated or the job's share weight changed. As the job's id remained the same, the miner submitted the solution to the old id which had already been marked as resolved.
**invalid shares**: This issue has the same root cause as the stale jobs issue. But, in this case, the job hadn't been marked as resolved and the solution was calculated for a different timestamp.
The solution is to generate a random id for each `MinerJob`. But we need an id for each tx …
> fix: Fix stale jobs, invalid jobs, and invalid share errors

- txstratum/cli.py
- txstratum/utils.py
Example:
```
2021-03-05 16:06.09 [error    ] Exception in callback TxMiningManager._job_timeout_if_possible(<txstratum.jo...t 0x10a722e50>) handle=<TimerHandle when=10 TxMiningManager._job_timeout_if_possible(<txstratum.jo...t 0x10a722e50>)>
Traceback (most recent call last):
File "/Users/msbrogli/.pyenv/versions/3.8.2/lib/python3.8/asyncio/events.py", line 81, in _run
self._context.run(self._callback, *self._args)
File "/Users/msbrogli/Hathor/tx-mining-service/txstratum/manager.py", line 269, in _job_timeout_if_possible
raise Exception('Testing')
Exception: Testing
```
> fix: Log asyncio's unhandled exceptions

- .github/workflows/docker.yml
- We should push images to ECR with tags of `dev-*`, `staging-*`, and `v*`. `staging-*` on commits to  `master`, `v*` when tags are created, and `dev-*` in any other case.
- We should only push images with tags `v*` to Dockerhub
We will be deploying a new instance of tx-mining-service that will use those images from ECR.
> ci: push images to ECR

- tests/test_manager.py
- txstratum/jobs.py
- txstratum/protocol.py
- We should stop getting this exception:
```
txstratum.utils - ERROR - 2022-01-12 11:41.38 [error    ] Fatal error: protocol.data_received() call failed. protocol=<txstratum.protocol.StratumProtocol object at 0x7fc5e661f610> transport=<_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
File "/home/luislhl/.pyenv/versions/3.8.3/lib/python3.8/asyncio/selector_events.py", line 860, in _read_ready__data_received
self._protocol.data_received(data)
File "/home/luislhl/Workspace/hathor/tx-mining-service/txstratum/utils.py", line 114, in data_received
self.line_received(line)
File "/home/luislhl/Workspace/hathor/tx-mining-service/txstratum/utils.py", line 155, in line_received
self.json_received(data)
File …
```
> fix: store the mining start time in the jobs

- txstratum/protocol.py
We should be able to get the miner version from cgminers.
Previously we couldn't, because they only accept integers as ids for messages, and we were using a string as id. This is what causes this behavior there: https://github.com/HathorNetwork/cgminer/blob/master/util.c#L2468
To achieve this, his PR implements a better way to manage the messages that are waiting return from the miners.
I didn't test this with `ccminer` miners. But we shouldn't have problems since their implementation to handle the `get_version` message is almost the same as the `cpuminer` one. This can be seen in https://github.com/HathorNetwork/ccminer/blob/master/util.cpp#L1683 and https://github.com/HathorNetwork/cpuminer/blob/master/util.c#L1408
> fix: get miner version from cgminers

- txstratum/cli.py
We accidentally broke logging config in https://github.com/HathorNetwork/tx-mining-service/pull/53 because we changed  the order in which things happen
Now we should have the logging working again.
> fix: logging config

- txstratum/prometheus.py
- txstratum/protocol.py
- txstratum/pubsub.py
- We should have a metric `miner_up` in Prometheus with value `1`  if the miner is connected to tx-mining-service, and `0` if it is disconnected
This solution requires that we never use the same address in 2 different miners, otherwise we will not be able to differentiate their metrics.
In some cases we need to know if the miner is down to filter them out in Prometheus queries and alerts
> feat: metrics to detect if miner is up

- .github/workflows/main.yml
- tests/fixtures/expected_prometheus_metrics.prom
Tests should run on PRs that were just opened. We merged a PR with failed tests (https://github.com/HathorNetwork/tx-mining-service/pull/57) because the tests didn't run and nobody noticed.
> ci: fix Github Actions job trigger

- txstratum/toi_client.py
- Add event name on log to prevent `TypeError` exception
> fix: log missing event name

- tests/test_api.py
- txstratum/api.py
> feat: return success on repeated job submission

- Dockerfile
- docs/apidocs.yml
- pyproject.toml
* fix: missing dependencies
* chore: bump version v0.6.4
> Release v0.6.4

- poetry.lock
- pyproject.toml
- tests/test_manager.py
- txstratum/jobs.py
- txstratum/manager.py
closes: https://github.com/HathorNetwork/tx-mining-service/issues/77
depends on: https://github.com/HathorNetwork/python-hathorlib/pull/10
- Tx Mining Service should not stop pushing blocks in case one of the pushes gets an error from the fullnode
- It should try again for 3 times to push a transaction if it gets error from the fullnode
- It should just ignore errors when pushing blocks
Linters are failing currently because this code depends on the new hathorlib. This PR is blocked by the lib PR
> fix: handle hathor-core errors when submitting blocks

- tests/test_api.py
- tests/test_utils.py
- txstratum/api.py
- txstratum/cli.py
- txstratum/exceptions.py
- txstratum/middleware.py
- txstratum/utils.py
- We must be able to block from old wallet versions. This is done getting the wallet version from the user agent and comparing with the minimum allowed version set in the command line argument.
- This should be possible for wallet desktop, mobile and headless.
> feat: add min_version parameter for all three wallets and block requests from old ones

- .github/workflows/docker.yml
See this https://github.com/HathorNetwork/tx-mining-service/pull/84 for more details about the docker build failing.
- We must remove the docker build for arm platform
> chore: temporarily remove docker build for arm

- poetry.lock
- pyproject.toml
- tests/test_api.py
- txstratum/api.py
- txstratum/jobs.py
- txstratum/utils.py
- Update python-hathorlib to v0.5.1. This version adds support for Feature Activation signal bits.
- Remove `tx_or_block_from_bytes()` function from utils, and use the one from `python-hathorlib` instead.
- Add `StructError` to API error handling, as this was changed in `python-hathorlib`.
> chore: update hathor-lib

- tests/test_api.py
- tests/test_healthcheck.py
- txstratum/api.py
- txstratum/cli.py
- txstratum/healthcheck.py
- txstratum/healthcheck/healthcheck.py
- txstratum/healthcheck/models.py
- txstratum/jobs.py
- txstratum/manager.py
We should have a new `/health` endpoint, that will implement a more complex health check which includes:
- Checking that there is at least 1 miner connected
- Checking that the miners have at least 1 job submitted in the last hour (submitting a job is different than mining a transaction, there should be submitted jobs even if no transactions are being mined)
- Checking that none of the jobs in the last 5 minutes failed
- Checking that the jobs aren't taking more than 10 seconds to be mined
- Checking the health of the Fullnode
- For now we will only make sure its `/v1a/version` endpoint is responding. In future PRs we will use the new yet-to-be-implemented `/v1a/health` endpoint of hathor-core.
> feat: health check

- tests/fixtures/expected_prometheus_metrics.prom
- txstratum/prometheus.py
- txstratum/protocol.py
- Reduce initial weight for hashrate estimator because cpuminers were taking too long to mine their first job.
- Increase the quantity of buckets for `txs_solved_weight` and `txs_timeout_weight` metrics, so we can analyze better the distribution.
- Add log to collect data for the miner's hashrate that is solving each transaction and block.
- Fix log
> feat: improve data collection of metrics

- txstratum/api.py
Developers who are implementing/testing new features in the hathor-core in a custom network might need to test things using the hathor-wallet. We currently have support for CORS headers (allowing localhost:3000 - the origin for the desktop wallet) in the hathor-core APIs but not in the tx mining service API.
- Add CORS headers to all API responses.
> feat: add CORS headers to all responses

- tests/fixtures/expected_prometheus_metrics.prom
- tests/test_manager.py
- tests/test_prometheus.py
- txstratum/prometheus.py
- txstratum/protocol.py
One possible improvement for our hashrate estimator is to consider the RTT value in the time to mine the job. Before we change the code to consider this rtt value, the first step is to calculate it and check if it influences the final hashrate estimation.
- Add RTT method estimator.
- Store RTT value for each miner in prometheus.
> feat: implement task to estimate RTT value for each miner

- txstratum/api.py
I had issues with CORS when trying to run a wallet-desktop with a local tx-mining-server running in docker. This PR fixes it. For more info, see [this comment](https://github.com/HathorNetwork/hathor-wallet/pull/710#discussion_r1894441789).
- Add `OPTIONS /submit-job` endpoint returning an empty success response.
> fix: add OPTIONS /submit-job endpoint for CORS

- Dockerfile
- pyproject.toml
The docker build was failing because poetry v2 was released, requiring a change in our config. We now have to explicitly tell poetry that our project is not a package ([docs](https://python-poetry.org/docs/basic-usage/#operating-modes)).
- Explicitly set `package-mode = false` in the `pyproject.toml`.
- Fix a minor warning in the `Dockerfile`.
> fix: poetry build on docker

- txstratum/api.py
- Update branch `dev` with latest commits in `master`
> Sync `master` with `dev`

- poetry.lock
- pyproject.toml
- Bump python hathorlib to v0.7.0
**Note:** I had to upgrade also the aiohttp package because python-hathorlib already uses a newer version (it was updated [here](https://github.com/HathorNetwork/python-hathorlib/pull/46))
**Note2:** I'm using python 3.12, not sure if it has any impact.
> chore: bump python hathorlib to v0.7.0

- poetry.lock
- pyproject.toml
- Update hathorlib to v0.8.1
- Bump version to v16.0.1
> chore: update python-hathorlib to v0.8.1

- txstratum/jobs.py
In the wallet lib integration tests I was able to correctly build and mine transactions with nano header for `initialize` and `bet` methods (using the Bet blueprint) but the `set_result` tx was always failing.
The error was that the transaction mining service identified the `set_result` tx as the same as the `initialize` tx because both didn't have inputs/outputs/tokens and we were using `tx. get_funds_hash` for the job uuid, so it was just returning the same nonce, which was wrong.
- Use `calculate_hash ` instead of `get_funds_hash`.
> fix: use calculate_hash for job uuid to prevent different txs with the same uuid

- poetry.lock
- pyproject.toml
- Update hathorlib to `v0.9.0`
- Bump package to `v0.17.0`
> chore: update python-hathorlib to v0.9.0

- poetry.lock
- pyproject.toml
- Update hathorlib to v0.9.1
- Bump package to v0.17.0
> chore: update python-hathorlib to v0.9.1
